"""empty message

Revision ID: 49f6f8c2dcf
Revises: 124f1c1d678
Create Date: 2018-01-18 10:31:14.319359

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '49f6f8c2dcf'
down_revision = '124f1c1d678'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sqlalchemy_utils.types.password.PasswordType(max_length=1137), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    ### end Alembic commands ###
